# Generated by Django 5.0.3 on 2024-04-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_boost_type_core_auto_click_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='brs_points',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='boost',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'casual'), (1, 'auto')], default=0),
        ),
        migrations.AlterField(
            model_name='core',
            name='lvl',
            field=models.IntegerField(default=1),
        ),
    ]
