# Generated by Django 5.0.3 on 2024-04-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_core_brs_points_alter_boost_type_alter_core_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='brs_power',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='boost',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'auto'), (0, 'casual')], default=0),
        ),
        migrations.AlterField(
            model_name='core',
            name='brs_points',
            field=models.FloatField(default=0),
        ),
    ]
