# Generated by Django 5.0.3 on 2024-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_core_brs_power_alter_boost_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='brs_power',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='boost',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'brs'), (0, 'casual'), (1, 'auto')], default=0),
        ),
    ]
